Repository yuchen0515/2022-Competition-CUDAOutOfMemory, pull requests merged in 2022-07, with the labels that each got.

#1 Feature #1 - clean up model / inference / preprocess
  README.md
  data_preprocess/preprocess.py
  inference/config.py
  inference/dataset_inference.py
  inference/inference.py
  inference/model.py
  inference/perplexity.py
  inference/search_method.py
  inference/word_converter.py
  model/config.py
  model/data.py
  model/evaluation.py
  model/model.py
  model/perplexity.py
  model/train.py
  requirements.txt
Labels: enhancement, preprocess, inference, model, dev

#3 Feature #3 - update README
  README.md
Labels: documentation, enhancement, dev

#5 Feature #5 - format all code with PEP8 guidelines
  api.py
  data_preprocess/data_preprocess.py
  data_preprocess/external_data_preprocess.py
  inference/config.py
  inference/dataset_inference.py
  inference/inference.py
  inference/model.py
  inference/perplexity.py
  inference/search_method.py
  inference/word_converter.py
  model/config.py
  model/data.py
  model/evaluation.py
  model/model.py
  model/perplexity.py
  model/train.py
Labels: enhancement, dev
